name: CI

on:
  pull_request:

jobs:
  linux-64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false

      - name: Run setup script
        shell: pixi exec --spec sed -- bash -e {0}
        run: |
          sed -i "s?main?${{ github.event.pull_request.head.ref }}?g" pixi-setup.sh
          sed -i "s?init.sh | bash?init.sh | sed \'s,main,${{ github.event.pull_request.head.ref }},g\' bash??" pixi-setup.sh
          ./pixi-setup.sh

  osx-64:
    runs-on: macos-13
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false

      - name: Run setup script
        shell: pixi exec --spec sed -- zsh -e {0}
        run: |
          sed -i "s?main?${{ github.event.pull_request.head.ref }}?g" pixi-setup.sh
          sed -i "s?init.sh | bash?init.sh | sed \'s,main,${{ github.event.pull_request.head.ref }},g\' bash??" pixi-setup.sh
          ./pixi-setup.sh

  osx-arm64:
    runs-on: macos-14
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false

      - name: Run setup script
        shell: pixi exec --spec sed -- zsh -e {0}
        run: |
          sed -i "s?main?${{ github.event.pull_request.head.ref }}?g" pixi-setup.sh
          sed -i "s?init.sh | bash?init.sh | sed \'s,main,${{ github.event.pull_request.head.ref }},g\' bash??" pixi-setup.sh
          ./pixi-setup.sh
