name: CI

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false

      - name: Run setup script
        shell: pixi exec --spec sed --spec bash -- bash -e {0}
        env:
          INSTALL_TYPE: full
        run: |
          sed -i "s?main?${{ github.event.pull_request.head.ref }}?g" pixi-setup.sh
          sed -i "s?init.sh | bash?init.sh | sed 's,main,${{ github.event.pull_request.head.ref }},g' | bash?" pixi-setup.sh
          printf "\n1\n" | ./pixi-setup.sh
